# Generated by Django 4.2.2 on 2023-06-19 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_otpverification_expired_otpverification_verified_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vendorprofile',
            name='age',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='vendorprofile',
            name='city',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='vendorprofile',
            name='name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='vendorprofile',
            name='working_or_studying',
            field=models.CharField(blank=True, choices=[('working', 'Working'), ('studying', 'Studying'), ('other', 'Other')], max_length=255, null=True),
        ),
    ]
